name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./tests
        run: docker-compose up --exit-code-from integration-tests integration-tests
