name: Integration Tests

on:  [push, pull_request]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.204
          
      - name: Integration Tests
        working-directory: ./tests/Rabbiter.IntegrationTests
        run: ./init.sh
        
      - name: Print docker status
        if: always()
        run: |
          docker ps
          docker stats --no-stream --all
          
      - name: Upload integration test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
            name: integration-test-results
            path: ./tests/Rabbiter.IntegrationTests/TestResults
