name: Integration Tests

on:  [push, pull_request]

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.204
          
      - name: Unit Tests
        run: dotnet test -c Release --verbosity normal --logger trx ./tests/Rabbiter.UnitTests/

      - name: Unit Tests Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
            name: unit-test-results
            path: ./tests/Rabbiter.UnitTests/TestResults